        PROGRAM types
        
        REAL TEMP, PRESS, VOLUME, MU, RATE, EPSIL, DELTAX, RATE1, RATE2
        INTEGER ZETA, TIME, DIST, GRAV, CBOIL, FBOIL, NUMINT
        DOUBLE PRECISION ALPHA, BETA, EARTH, MARS
        CHARACTER*10 STRA, STRB, STRC, NAME*20, NAME1*20, NAME2*20, 
     &   NAME3, STREET*30, CITY*15, STATE*2, COURSE
        PARAMETER (MARS=1.5D10,
     &   CBOIL=100, FBOIL=212, EPSIL=1.0E-5, DELTAX=0.001, NUMINT=500, 
     &   COURSE='CPSC 141')
        DATA RATE1, RATE2, RATE, GRAV, EARTH / -1.23, 2.33, 3.4, 32, 
     &   1.2D12/

        WRITE (*,*) RATE, GRAV, EARTH, MARS, CBOIL, FBOIL, EPSIL,
     &   DEATAX, NUMINT, COURSE, RATE1, RATE2
        WRITE (*,*) INT(RATE1), ABS(RATE1), COS(RATE1), DBLE(RATE1), 
     &   DPROD(RATE1, RATE2), EXP(RATE1), MOD(CBOIL, 3)
    
        

        END PROGRAM types